send_sms:
  description: Sends sms
  fields:
    number:
      description: Phone number
      example: 067683837
    message:
      description: message text
      example: Hello from HASS

dial:
  description: Dials the voice number
  fields:
    number:
      description: Phone number
      example: 067683837

lte_up:
  description: Enables LTE connection by name
  fields:
    connection_name:
      description: Connection name created by NetworkManager
      example: Unite

lte_down:
  description: Disables active LTE connection
