send_sms:
  description: Sends sms
  fields:
    number:
      description: Phone number
      example: 067683837
    message:
      description: message text
      example: Hello from HASS

delete_sms:
  description: Delete sms
  fields:
    sms_path:
      description: Sms path
      example: /org/freedesktop/ModemManager1/SMS/41

dial:
  description: Dials the voice number
  fields:
    number:
      description: Phone number
      example: 067683837

lte_up:
  description: Enables LTE connection by name configured for this service

lte_down:
  description: Disables active LTE connection
